services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DIALECT: postgresql
      DB_PORT: 5432
      DB_NAME: basseno_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      - pgadmin

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: basseno_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Access pgAdmin via http://localhost:5050
    networks:
      - app

volumes:
  db-data:

networks:
  app:
