### Auth Endpoints

# Generate token (Tokens expire after 1 day!)
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

### User Endpoints

# Register a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "newUser",
  "email": "newuser@example.com",
  "password": "securepassword",
  "firstname": "John",
  "lastname": "Doe",
  "address": "123 Example St",
  "city": "Example City",
  "plz": "12345",
  "salutation": "Mr."
}

###

# Get user by ID (hat token mit ID 9)
GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZXhwIjoxNzMzNjgzNzU4LCJ1c2VybmFtZSI6Im5ld1VzZXIiLCJyb2xlIjoidXNlciJ9.u6tGtN9FDkF63ecNr-oaZQ9OMJ6d6yF-p3b4IyrYnMA

###

# Get all users (Admin access required)
GET http://localhost:8080/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzNjgzOTk1LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.yoiFSl1KtJigNJbQ7ftg2oJPq268tCYQIAdshBurUrs

###

# Update user profile
PUT http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5IiwiZXhwIjoxNzMzNjgzNzU4LCJ1c2VybmFtZSI6Im5ld1VzZXIiLCJyb2xlIjoidXNlciJ9.u6tGtN9FDkF63ecNr-oaZQ9OMJ6d6yF-p3b4IyrYnMA
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@example.com",
  "password": "password",
  "newPassword": "newpassword"
}

###

# Admin updates a user
PUT http://localhost:8080/api/users/admin/1
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "username": "adminupdateduser",
  "email": "adminupdated@example.com",
  "password": "adminpassword123"
}

###

# Admin deletes a user
DELETE http://localhost:8080/api/users/admin/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzNjgzOTk1LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.yoiFSl1KtJigNJbQ7ftg2oJPq268tCYQIAdshBurUrs
