### Auth and User Endpoints

# Generate ADMIN TOKEN (Tokens expire after 1 day!)
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

# Generate USER TOKEN (Tokens expire after 1 day!)
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
"username": "user1",
"password": "password"
}

###

# Register a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "newUser",
  "email": "newuser@example.com",
  "password": "password",
  "firstname": "John",
  "lastname": "Doe",
  "address": "123 Example St",
  "city": "Example City",
  "plz": "12345",
  "salutation": "Mr."
}

###

# Get user by ID (hat token mit ID 2)
GET http://localhost:8080/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzMzODczMjIwLCJ1c2VybmFtZSI6InVzZXIxIiwicm9sZSI6InVzZXIifQ._fSXTNdYfhichBOwDcFRSgguPEXKj4UPe4QSZfnXnns

###

# Admin: Get all users
GET http://localhost:8080/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzODU4MDgxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0._sGDA4xq6LprAyZFdq5wu80XfVgJy6M3sVCbpJ55Wtk

###

# Admin: Get all users (with user token, should fail with 403)
GET http://localhost:8080/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzMzODczMjIwLCJ1c2VybmFtZSI6InVzZXIxIiwicm9sZSI6InVzZXIifQ._fSXTNdYfhichBOwDcFRSgguPEXKj4UPe4QSZfnXnns

###

# Update user profile (hat Token mit ID 17)
PUT http://localhost:8080/api/users/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxNyIsImV4cCI6MTczMzg3NDA5NywidXNlcm5hbWUiOiJuZXdVc2VyIiwicm9sZSI6InVzZXIifQ.fCcHSy2-t6y5xstS5L2GtHPCp2OHpFbGZQpQ_MFGIlg
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@example.com",
  "firstname": "Updatedname",
  "lastname": "Updatedlastname",
  "address": "123 Updated St",
  "city": "Updated City",
  "plz": "54321",
  "salutation": "Mrs.",
  "password": "password",
  "newPassword": "password"
}

###

# Admin: update a user TODO: fix
PUT http://localhost:8080/api/users/admin/1
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "username": "adminupdateduser",
  "email": "adminupdated@example.com",
  "password": "adminpassword123"
}

###

# Admin deletes a user
DELETE http://localhost:8080/api/users/admin/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzODU4MDgxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0._sGDA4xq6LprAyZFdq5wu80XfVgJy6M3sVCbpJ55Wtk

###

# Admin deletes a user (with user token, should fail with 403) TODO: shouldn't work
DELETE http://localhost:8080/api/users/admin/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4IiwiZXhwIjoxNzMzODU5NDM5LCJ1c2VybmFtZSI6ImVuZXNvbiIsInJvbGUiOiJ1c2VyIn0.deGge3KCeNBezbOeQlJ_JX9kAckwNdedVTbhBnYTxUY


// User token (ID 2)
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZXhwIjoxNzMzODczMjIwLCJ1c2VybmFtZSI6InVzZXIxIiwicm9sZSI6InVzZXIifQ._fSXTNdYfhichBOwDcFRSgguPEXKj4UPe4QSZfnXnns
// Admin token
// eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzODU4MDgxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0._sGDA4xq6LprAyZFdq5wu80XfVgJy6M3sVCbpJ55Wtk

