### Auth and User Endpoints

# Generate ADMIN TOKEN (Tokens expire after 1 day!)
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

###

# Generate USER TOKEN (Tokens expire after 1 day!)
POST http://localhost:8080/api/auth/token
Content-Type: application/json

{
"username": "newUser",
"password": "password"
}

###

# REGISTER a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "newUser",
  "email": "newuser@example.com",
  "password": "password",
  "firstname": "John",
  "lastname": "Doe",
  "address": "123 Example St",
  "city": "Example City",
  "plz": "12345",
  "salutation": "Mr."
}

###

# Get user by ID (hat token mit ID 22)
GET http://localhost:8080/api/users/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsImV4cCI6MTczMzkyOTg2OCwidXNlcm5hbWUiOiJuZXdVc2VyIiwicm9sZSI6InVzZXIifQ.eunFXHgzyTx7ov9be7b8lmSaq6u_oashHTWHUoQsmpg

###

# Admin: Get all users
GET http://localhost:8080/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzOTI5ODA1LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.WnzeWRlzL62kivFT3dWYP-STY8ds6N_WPkgqChd7cU8

###

# Admin: Get all users (with user token, should fail with 403)
GET http://localhost:8080/api/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsImV4cCI6MTczMzkyOTg2OCwidXNlcm5hbWUiOiJuZXdVc2VyIiwicm9sZSI6InVzZXIifQ.eunFXHgzyTx7ov9be7b8lmSaq6u_oashHTWHUoQsmpg

###

# Update user profile (hat Token mit ID 22)
PUT http://localhost:8080/api/users/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsImV4cCI6MTczMzkyOTg2OCwidXNlcm5hbWUiOiJuZXdVc2VyIiwicm9sZSI6InVzZXIifQ.eunFXHgzyTx7ov9be7b8lmSaq6u_oashHTWHUoQsmpg
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@example.com",
  "firstname": "Updatedname",
  "lastname": "Updatedlastname",
  "address": "123 Updated St",
  "city": "Updated City",
  "plz": "54321",
  "salutation": "Mrs.",
  "password": "password",
  "newPassword": "password"
}

###

# Admin: update a user
PUT http://localhost:8080/api/users/admin/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzOTI5ODA1LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.WnzeWRlzL62kivFT3dWYP-STY8ds6N_WPkgqChd7cU8
Content-Type: application/json

{
  "username": "adminupdateduser",
  "email": "adminupdateduser@example.com",
  "firstname": "adminupdatedname",
  "lastname": "adminupdatedlastname",
  "address": "123 Admin Updated St",
  "city": "Admin Updated City",
  "plz": "54321",
  "salutation": "Mrs."
}

###

# Admin deletes a user
DELETE http://localhost:8080/api/users/admin/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzMzOTI5ODA1LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.WnzeWRlzL62kivFT3dWYP-STY8ds6N_WPkgqChd7cU8

###

# Admin deletes a user (with user token, should fail with 403)
DELETE http://localhost:8080/api/users/admin/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyMiIsImV4cCI6MTczMzkyOTg2OCwidXNlcm5hbWUiOiJuZXdVc2VyIiwicm9sZSI6InVzZXIifQ.eunFXHgzyTx7ov9be7b8lmSaq6u_oashHTWHUoQsmpg
